### ISSUE TITLE
Capacitors on V1.1 boards

### ISSUE THREAD

**Issue by jalim** [thorrak/thorrak_hardware#2]
I notice you've added 4 capacitors on the latest version of the main controller boards, may I ask what these achieve?

I've got a couple of the original PCBs (yet to solder) and wondering if there's enough reason to order the new ones?

**Comment by lbussy** [comment]
The capcitors serve to decouple the power and help avoid circuit noise.

**Comment by jalim** [comment]
Thanks @lbussy, finally managed to wade through the homebrewtalk forum and find Thorrak's explanation of the differences.
